In [22]:
pip install git+https://github.com/amjams/FeatBoost.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/amjams/FeatBoost.git to /tmp/pip-req-build-wfm22w9b
  Running command git clone --filter=blob:none --quiet https://github.com/amjams/FeatBoost.git /tmp/pip-req-build-wfm22w9b
  Resolved https://github.com/amjams/FeatBoost.git to commit be019d2244c4d910cfc66202933f1a570a57a47a
  Preparing metadata (setup.py) ... done


In [23]:
from google.colab import files
uploaded = files.upload()

Saving KC1.csv to KC1 (1).csv


In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [28]:
dataset=pd.read_csv('KC1 (1).csv')

In [29]:
dataset.head()

loc  v(g)  ev(g)  iv(g)      n       v     l      d      i         e  ...  \
0   1.1   1.4    1.4    1.4    1.3    1.30  1.30   1.30   1.30      1.30  ...   
1   1.0   1.0    1.0    1.0    1.0    1.00  1.00   1.00   1.00      1.00  ...   
2  83.0  11.0    1.0   11.0  171.0  927.89  0.04  23.04  40.27  21378.61  ...   
3  46.0   8.0    6.0    8.0  141.0  769.78  0.07  14.86  51.81  11436.73  ...   
4  25.0   3.0    1.0    3.0   58.0  254.75  0.11   9.35  27.25   2381.95  ...   

   lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  uniq_Opnd  \
0       2          2        2                  2      1.2        1.2   
1       1          1        1                  1      1.0        1.0   
2      65         10        6                  0     18.0       25.0   
3      37          2        5                  0     16.0       28.0   
4      21          0        2                  0     11.0       10.0   

   total_Op  total_Opnd  branchCount  defects  
0       1.2         1.2          1.4        0  
1       1.0         1.0          1.0        1  
2     107.0        64.0         21.0        1  
3      89.0        52.0         15.0        1  
4      41.0        17.0          5.0        1  

[5 rows x 22 columns]

In [30]:
X=dataset.iloc[:,1: 21].values
y=dataset.iloc[:, 21].values

In [31]:
print(X)

[[  1.4   1.4   1.4 ...   1.2   1.2   1.4]
 [  1.    1.    1.  ...   1.    1.    1. ]
 [ 11.    1.   11.  ... 107.   64.   21. ]
 ...
 [  1.    1.    1.  ...   3.    1.    1. ]
 [  1.    1.    1.  ...   9.    8.    1. ]
 [  2.    1.    2.  ...  18.    9.    3. ]]


In [32]:
print(y)

[0 1 1 ... 0 0 0]


In [33]:
from featboost import FeatBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier()

In [34]:
clf = FeatBoostClassifier(estimator=clf)
clf.fit(X, y)
clf.feature_importances_array_



ATTENTION: Reset occured because of selected twice!
Infinite loop: No more resets this time!
Stopping Condition triggered at iteration number: 2
Selected variables so far:
[15, 16]


array([[0.03380741, 0.02403058, 0.03743555, 0.05234965, 0.05362154,
        0.04711392, 0.06470473, 0.05433642, 0.05473465, 0.04511929,
        0.05858176, 0.0744934 , 0.04894617, 0.0566146 , 0.01770523,
        0.06243236, 0.06218907, 0.05556792, 0.05966171, 0.03655405],
       [0.03603047, 0.03232439, 0.03805124, 0.05007395, 0.0531244 ,
        0.05210272, 0.0538442 , 0.05492205, 0.05003752, 0.04190161,
        0.05106612, 0.09407735, 0.04925404, 0.05632173, 0.02737205,
        0.06120567, 0.05520971, 0.05401823, 0.05209063, 0.03697193],
       [0.03376323, 0.02574652, 0.0407491 , 0.06389214, 0.05045681,
        0.04884231, 0.06462505, 0.05192772, 0.0521942 , 0.04279916,
        0.05040132, 0.07186876, 0.04704219, 0.05957846, 0.01908524,
        0.05888057, 0.06001741, 0.05639522, 0.06553782, 0.03619676],
       [0.03090172, 0.02475592, 0.03363869, 0.05618426, 0.05292413,
        0.05328589, 0.0528446 , 0.05834057, 0.05643346, 0.0429075 ,
        0.05219032, 0.10944676, 0.04587456, 0

In [35]:
clf.selected_subset_

[15, 16]